<!DOCTYPE html>
<html>

<link href="/css/style.css" type="text/css" rel="stylesheet">

<title>Wobbesheerd :: Contact</title>
<style type="text/css"></style></head>
<body>


<div id="container">
	
	<div id="header">
		
		
		
	</div>
	
	<div id="content_wrapper">		
		<div id="content_wrapper_top">			
			<div id="content_wrapper_bottom">
				<div id="content">
					<div id="menu">
						
	<ul>
					<li><a href="#">Homepage</a>				</li>
					<li><a href="#">Faciliteiten</a>				</li>
					<li><a href="#">Uw visie</a>				</li>
					<li><em><a href="./bestanden/Wobbesheerd __ Contact.html">Contact</a></em>				</li>
					<li><a href="#">Route</a>				</li>
					<li><a href="#">Omgeving</a>				</li>
			
	</ul>
	
						
					</div>
					
					<div id="text">
					        <h1>Contact</h1>
					        <p><img style="float: right;" src="./bestanden/contact.jpg" alt="Contact" width="300" height="199"></p>
<p>S.R.&nbsp;Wobbes</p>
<p>Hoofdstraat 216<br> 9828 PD Oostwold (gem Leek, Gr.)<br> Tel: 050-5515623<br> Mob: 06-15596766</p>
<p>email: <a href="mailto:info@wobbesheerd.nl">info@wobbesheerd.nl</a></p>
<p>Als u vragen heeft of op zoek bent naar verdere mogelijkheden, neemt u dan contact op met ons. Wij staan u graag te woord.</p>
<p>Met vriendelijke groet,<br>Reinier Wobbes</p>
<p><a href="mailto:info@wobbesheerd.nl">info@wobbesheerd.nl</a></p>
<p>* <span style="font-size: xx-small;">Is niet verplicht&nbsp;</span></p>

<!--
  This form is automaticly being generated by FormHandler v3.
  See for more info: http://www.formhandler.net
  This credit MUST stay intact for use
-->
<form name="FormHandler" method="post" action="./bestanden/Wobbesheerd __ Contact.html">
<input type="hidden" name="FormHandler_submit" id="FormHandler_submit" value="1">

<table border="0" cellspacing="0" cellpadding="3">

<tbody><tr> 
	<td valign="top">Uw naam : &nbsp;</td> 
	<td valign="top"><input type="text" name="Uwnaam" id="Uwnaam" value="" size="20">   &nbsp;</td> 
</tr>
<tr> 
	<td valign="top">Email : &nbsp;</td> 
	<td valign="top"><input type="text" name="Email" id="Email" value="" size="30">   &nbsp;</td> 
</tr>
<tr> 
	<td valign="top">Telefoon *  : &nbsp;</td> 
	<td valign="top"><input type="text" name="Telefoon" id="Telefoon" value="" size="20">   &nbsp;</td> 
</tr>
<tr> 
	<td valign="top">Bericht : &nbsp;</td> 
	<td valign="top"><textarea name="Bericht" id="Bericht" cols="40" rows="10"></textarea>   &nbsp;</td> 
</tr>
<tr> 
	<td valign="top">  &nbsp;</td> 
	<td valign="top"><input type="submit" value="Verzend" name="button1" id="button1">   &nbsp;</td> 
</tr>
</tbody></table>
</form>
<!--
  This form is automaticly being generated by FormHandler v3.
  See for more info: http://www.formhandler.net
-->					</div>
				</div>
			</div>			
		</div>		
	</div>
	
	<div id="footer">
		<address>							
			Hoofdstraat 216<br>
			9828 PD Oostwold<br>
			Tel: 050-5515623<br>
			Mob. 06-15596766 <br>
			Email: <span class="email"><a href="mailto:info@wobbesheerd.nl">info@wobbesheerd.nl</a></span><br>
		</address>		
	</div>
	
</div>



</body></html>